name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('project.clj') }}
          restore-keys: |
            m2-
      - name: Test
        run: lein test
