name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          bb: latest          
          cli: 1.11.1.1182

      - name: Run clj tests
        run: ./bin/kaocha clj

      - name: Run cljs tests
        run: ./bin/kaocha cljs

      - name: Run bb clj tests
        run: bb test:clj

      - name: Run bb cljs tests
        run: bb test:cljs        

